// site/src/routes/components/Control.svelte
<script lang="ts">
	import type { TagInfo } from '$lib/types/repo';

	import { getContext } from 'svelte';
	import type { Writable } from 'svelte/store';
	import type { SortDirection, SortType } from '../type';
	import TagChip from './TagChip.svelte';
	import Select from '$lib/components/Select.svelte';
	import TextInput from '$lib/components/TextInput.svelte';
	import Button from '$lib/components/Button.svelte';

	export let tagInfo: TagInfo;

	let sortType: Writable<SortType> = getContext('sortType');
	let sortDirection: Writable<SortDirection> = getContext('sortDirection');
	let filter: Writable<string> = getContext('filter');

	let tags = tagInfo.filter((tag) => tag.count >= 2).sort((a, b) => b.count - a.count);
	let filterOpen = true;
</script>

<div class="flex flex-col gap-1">
	<div class="flex flex-col w-full">
		<div class="flex items-center">
			<span class="text-white">Sort type</span>
			<Select
				data={[
					['star', 'star'],
					['created', 'createdAt'],
					['updated', 'lastCommit'],
					['Name(repo)', 'repoName'],
					['Name(owner)', 'ownerName']
				]}
				bind:value={$sortType}
			/>
		</div>
		<div class="flex items-center">
			<span class="text-white">Sort order</span>
			<Select
				data={[
					['asc', 'asc'],
					['desc', 'desc']
				]}
				bind:value={$sortDirection}
			/>
		</div>
	</div>
	<div>
		<span class="text-white">Search</span>
		<TextInput bind:value={$filter} />
	</div>
	<div>
		<span class="text-white">Filter</span>
		<Button
			on:click={() => {
				filterOpen = !filterOpen;
			}}>Toggle</Button
		>
		<div
			class={`flex flex-row flex-wrap gap-1 h-[70vh] overflow-x-hidden overflow-y-auto ${
				filterOpen ? '' : 'hidden'
			}`}
		>
			{#each tags as tag (tag.tag)}
				<TagChip tag={tag.tag} text={`${tag.tag} (${tag.count})`} />
			{/each}
		</div>
	</div>
</div>

// site/app/components/Control.tsx
"use client";
import { ToggleGroup } from "@/components/ToggleGroup";
import {
  SortOrder,
  SortType,
  tagInfoAtom,
  useSearchText,
  useSortOrder,
  useSortType,
  useTagFilter,
} from "../page_store";
import { Select } from "@/components/Select";
import { useState } from "react";
import { useAtom } from "jotai";
import { Chip } from "@/components/Chip";

export function Control() {
  const [sortType, setSortType] = useSortType();
  const [sortOrder, setSortOrder] = useSortOrder();
  const [searchText, setSearchText] = useSearchText();
  const [, setTagFilter] = useTagFilter();
  const [tagInfo] = useAtom(tagInfoAtom);

  const [inputText, setInputText] = useState(searchText);
  const [filterOpen, setFilterOpen] = useState(false);

  return (
    <div className="flex flex-col gap-1">
      <div className="flex flex-col w-full">
        <div className="flex items-center ">
          <span className="text-white">Sort type</span>
          <Select
            value={sortType}
            items={[
              ["Star", "star"],
              ["Created", "createdAt"],
              ["Last commit", "lastCommit"],
              ["Name(repo)", "repoName"],
              ["Name(owner)", "ownerName"],
            ]}
            onChange={(value) => {
              if (value) {
                setSortType(value as SortType);
              }
            }}
          />
        </div>
        <div className="flex items-center ">
          <span className="text-white">Sort order</span>
          <ToggleGroup
            value={sortOrder}
            items={[
              ["Desc", "desc"],
              ["Asc", "asc"],
            ]}
            onChange={(value) => {
              if (value) {
                setSortOrder(value as SortOrder);
              }
            }}
          />
        </div>
      </div>
      <div>
        <span className="text-white">Search</span>
        <input
          value={inputText}
          onChange={(e) => setInputText(e.currentTarget.value)}
          onKeyDown={(e: React.KeyboardEvent<HTMLInputElement>) => {
            if (e.nativeEvent.isComposing || e.key !== "Enter") return;
            setSearchText(e.currentTarget.value);
          }}
        />
      </div>
      <div>
        <span className="text-white">Filter</span>
        <button className="bg-white" onClick={() => setFilterOpen(!filterOpen)}>
          Toggle
        </button>
        <div
          className={`flex flex-row flex-wrap gap-1 h-[70vh] overflow-auto ${
            filterOpen ? "" : "hidden"
          }`}
        >
          {tagInfo.filter((tag) => tag.count >= 2).sort((a, b) =>
            b.count - a.count
          ).map((tag) => (
            <Chip
              key={tag.tag}
              className="bg-orange-800 hover:bg-orange-600"
              onClick={() => {
                setTagFilter([tag.tag]);
              }}
            >
              {JSON.parse(tag.tag).join("/")}({tag.count})
            </Chip>
          ))}
        </div>
      </div>
    </div>
  );
}
